version: "2"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./Crutchetzan:/var/www/html/  
        networks:
            - default
volumes:
    persistent: